apiVersion: v1
kind: Template
metadata:
  name: example-test
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: example-job
    spec:
      parallelism: 1
      completion: 1
      template:
        metadata:
          labels:
            name: example
        spec:
          containers:
            - name: execution-container
              image: 172.30.1.1:5000/example-project/example-image
          restartPolicy: Never
      replicas: 1
      selector:
        name: example
      strategy:
        type: Rolling
