kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: tests-claim
spec:
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi
 storageClassName: slow
 selector:
  name: registry